apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: open-webui-api-keys
  namespace: management
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: infisical-store
    kind: ClusterSecretStore
  target:
    name: open-webui-secrets
    creationPolicy: Owner
  data:
    - secretKey: virtual_key
      remoteRef:
        key: LITELLM_VIRTUAL_KEY
