apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-secret
  namespace: management

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: infisical-ghcr-store
    kind: ClusterSecretStore

  target:
    name: ghcr-secret
    creationPolicy: Owner

    template:
      type: kubernetes.io/dockerconfigjson

      data:
        .dockerconfigjson: |
          {
            "auths": {
              "ghcr.io": {
                "username": "{{ .GHCR_USERNAME }}",
                "password": "{{ .GHCR_TOKEN }}",
                "auth": "{{ printf "%s:%s" .GHCR_USERNAME .GHCR_TOKEN | b64enc }}"
              }
            }
          }

  data:

    - secretKey: GHCR_USERNAME
      remoteRef:
        key: GHCR_USERNAME

    - secretKey: GHCR_TOKEN
      remoteRef:
        key: GHCR_TOKEN

