apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infisical-release
  namespace: argocd
spec:
  project: default
  source:
    chart: infisical-standalone
    repoURL: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/v1/repo/
    targetRevision: 2.1.2
    helm:
      values: |
        backend:
          # Link to the manual secrets we made in Step 1
          existingSecret: infisical-secrets
          encryptionKeySecretKey: encryption-key
          jwtSecretSecretKey: jwt-secret

        # Configure persistence on your Ceph Cluster
        postgresql:
          enabled: true
          primary:
            persistence:
              enabled: true
              storageClass: ceph-block
              size: 10Gi

        redis:
          enabled: true
          master:
            persistence:
              enabled: true
              storageClass: ceph-block
              size: 2Gi

        # The Ingress for Traefik + Cert-Manager
        ingress:
          enabled: true
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            cert-manager.io/cluster-issuer: letsencrypt-production
          hosts:
            - host: secrets.mvgates.com
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
            - secretName: secrets-mvgates-tls
              hosts:
                - secrets.mvgates.com
  destination:
    server: https://kubernetes.default.svc
    namespace: infisical
