apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infisical-release
  namespace: argocd
spec:
  project: default
  source:
    chart: infisical-standalone
    # This is the specific URL for the STANDALONE chart
    repoURL: https://dl.cloudsmith.io/public/infisical/infisical-standalone/helm/v1/repo/
    targetRevision: 2.1.1 # This is the current stable Chart version
    helm:
      values: |
        backend:
          existingSecret: infisical-secrets
          encryptionKeySecretKey: encryption-key
          jwtSecretSecretKey: jwt-secret

        # We manually set the Image Tag you found
        image:
          tag: "v0.156.3"

        postgresql:
          enabled: true
          primary:
            persistence:
              enabled: true
              storageClass: ceph-block
              size: 10Gi

        redis:
          enabled: true
          master:
            persistence:
              enabled: true
              storageClass: ceph-block
              size: 2Gi

        ingress:
          enabled: true
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            cert-manager.io/cluster-issuer: letsencrypt-production
          hosts:
            - host: secrets.mvgates.com
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
            - secretName: secrets-mvgates-tls
              hosts:
                - secrets.mvgates.com
  destination:
    server: https://kubernetes.default.svc
    namespace: infisical
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
