apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghcr-secret
  namespace: management
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-ghcr-store
    kind: ClusterSecretStore
  target:
    name: ghcr-secret
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .dockerconfigjson }}"
  data:
    - secretKey: dockerconfigjson
      remoteRef:
        key: /services/ghcr
        property: dockerconfigjson
