apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: openclaw-web
  namespace: management
spec:
  entryPoints: [web, websecure]
  routes:
    - match: Host(`claw.mvgates.com`)
      kind: Rule
      middlewares:
        - name: openclaw-headers
        - name: webui-streaming
      services:
        - name: openclaw-service
          port: 80
  tls:
    secretName: openclaw-tls
