apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openclaw-agent-identity
  namespace: management

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: infisical-agents-store
    kind: ClusterSecretStore

  target:
    name: openclaw-agent-secret
    creationPolicy: Owner

  data:

    - secretKey: github_token
      remoteRef:
        key: GITHUB_TOKEN

    - secretKey: git_ssh_private_key
      remoteRef:
        key: GIT_SSH_PRIVATE_KEY

    - secretKey: git_user_name
      remoteRef:
        key: GIT_USER_NAME

    - secretKey: git_user_email
      remoteRef:
        key: GIT_USER_EMAIL

