apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: demo-mvgates-tls
  namespace: demo
spec:
  secretName: demo-mvgates-tls
  dnsNames:
    - demo.mvgates.com
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
