apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: neural-web-ingress
  namespace: demo
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`demo.mvgates.com`)
      kind: Rule
      services:
        - name: neural-web-svc
          port: 80
  tls:
    secretName: ai-mvgates-tls
