apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fitness-secrets
  namespace: fitness
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-store
  target:
    name: fitness-auth
    creationPolicy: Owner
  data:
    - secretKey: db-password
      remoteRef:
        key: /fitness/DB_PASSWORD
    - secretKey: django-secret
      remoteRef:
        key: /fitness/SECRET_KEY
