apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: fitness-headers
  namespace: fitness
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
      X-Forwarded-Host: "fitness.mvgates.com"
    contentTypeNosniff: false
