apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-ceph-tools
  namespace: rook-ceph
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rook-ceph-tools-binding
subjects:
  - kind: ServiceAccount
    name: rook-ceph-tools
    namespace: rook-ceph
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

