apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-websecure
  namespace: management
spec:
  entryPoints: [websecure]
  routes:
    - match: Host(`grafana.mvgates.com`)
      kind: Rule
      services:
        - name: grafana-external-svc
          port: 3000
          serversTransport: grafana-transport
  tls:
    secretName: grafana-mvgates-tls
