apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: grafana-transport
  namespace: monitoring
spec:
  insecureSkipVerify: true
  respondingTimeouts:
    readTimeout: 600s
    idleTimeout: 600s
