apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: webui-streaming
  namespace: management
spec:
  headers:
    customResponseHeaders:
      X-Accel-Buffering: "no"
      Cache-Control: "no-cache, no-transform"
      Connection: "keep-alive"
    customRequestHeaders:
      X-Forwarded-Proto: "https"
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: webui-transport
  namespace: management
spec:
  respondingTimeouts:
    readTimeout: 300s
    idleTimeout: 300s
