apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config
  namespace: ai-core
data:
  config.yaml: |
    general_settings:
      ui_enabled: true
      proxy_base_url: https://llmproxy.mvgates.com
      database_url: "os.environ/DATABASE_URL"
    litellm_settings:
      drop_params: true
      set_verbose: false
