apiVersion: apps/v1
kind: Deployment
metadata:
  name: litellm
  namespace: ai-core

spec:
  replicas: 1

  selector:
    matchLabels:
      app: litellm

  template:
    metadata:
      labels:
        app: litellm

    spec:

      containers:

        - name: litellm
          image: ghcr.io/berriai/litellm:main-latest

          args:
            - "--config=/app/config/config.yaml"
            - "--port=4000"
            - "--host=0.0.0.0"

          ports:
            - containerPort: 4000

          env:

            - name: DATABASE_URL
              value: "postgresql://postgres:postgres@litellm-postgres.ai-core.svc.cluster.local:5432/litellm?sslmode=disable"

            - name: STORE_MODEL_IN_DB
              value: "true"

            - name: LITELLM_MODE
              value: production

            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: litellm-api-keys
                  key: openai_key

            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: litellm-api-keys
                  key: gemini_key

            - name: LITELLM_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: litellm-api-keys
                  key: master_key


          volumeMounts:
            - name: config
              mountPath: /app/config
              readOnly: true

      volumes:
        - name: config
          configMap:
            name: litellm-confi
