apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: litellm-web
  namespace: ai-core

spec:
  entryPoints:
    - websecure

  routes:
    - match: Host(`llmproxy.mvgates.com`)
      kind: Rule
      services:
        - name: litellm-service
          port: 4000

  tls:
    secretName: llmproxy-tls

