apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: litellm-db-pvc
  namespace: ai-core
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: ceph-block
  resources:
    requests:
      storage: 5Gi
