apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-secrets
  namespace: ai-core
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: infisical-store
    kind: ClusterSecretStore
  target:
    name: litellm-api-keys
    creationPolicy: Owner
  data:
    - secretKey: openai_key
      remoteRef:
        key: OPENAI_API_KEY
    - secretKey: gemini_key
      remoteRef:
        key: GEMINI_API_KEY
    - secretKey: master_key
      remoteRef:
        key: LITELLM_MASTER_KEY
