apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-data
  namespace: vaultwarden
spec:
  accessModes:
    - ReadWriteOnce # Only one node can write to this disk at a time
  storageClassName: ceph-block
  resources:
    requests:
      storage: 5Gi
