# This tells the Prometheus chart to run in "Agent" mode
server:
  enabled: true
  replicaCount: 1

  remoteWrite:
    - url: "http://192.168.102.3:9090/api/v1/write"

  global:
    external_labels:
      cluster: homelab-k8s

alertmanager:
  enabled: false
prometheus-pushgateway:
  enabled: false

prometheus-node-exporter:
  enabled: true
kube-state-metrics:
  enabled: true
