#!/bin/bash

set -e

cd /data/workspace/homelab

BRANCH="ai-fix-$(date +%s)"

git checkout -b $BRANCH

git add .
git commit -m "AI proposed infrastructure fix"

git push origin $BRANCH

gh pr create \
    --title "AI proposed infrastructure fix" \
    --body "Automated fix generated by OpenClaw agent." \
    --head $BRANCH
