apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: immich-tls
  namespace: immich
spec:
  secretName: immich-tls-prod
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - photos.mvgates.com
