apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-db-secrets
  namespace: immich
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: infisical-store
    kind: ClusterSecretStore
  target:
    name: immich-db-keys
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: IMMICH_DB_PASSWORD
