apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph-cluster
  namespace: argocd
spec:
  project: default
  source:
    chart: rook-ceph-cluster
    repoURL: https://charts.rook.io/release
    targetRevision: 1.15.5
    helm:
      values: |
        operatorNamespace: rook-ceph
        cephClusterSpec:
          cephVersion:
            image: quay.io/ceph/ceph:v19.2.0

          cephConfig:
            global:
              auth_cluster_required: cephx
              auth_service_required: cephx
              auth_client_required: cephx
              ms_bind_msgr2: true
              ms_bind_msgr1: true

          dataDirHostPath: /var/lib/rook

          mon:
            count: 3
            allowMultiplePerNode: false

          mgr:
            count: 1
            dashboard:
              enabled: true
              ssl: true

          crashCollector:
            disable: false

          resources:
            mgr:
              limits:
                memory: "512Mi"
              requests:
                cpu: "100m"
                memory: "256Mi"
            mon:
              limits:
                memory: "1024Mi"
              requests:
                cpu: "100m"
                memory: "512Mi"
            osd:
              limits:
                memory: "2Gi"
              requests:
                cpu: "200m"
                memory: "1Gi"
            prepareosd:
              limits:
                memory: "400Mi"
              requests:
                cpu: "100m"
                memory: "200Mi"
            crashcollector:
              limits:
                memory: "64Mi"
              requests:
                cpu: "10m"
                memory: "32Mi"
            cleanup:
              limits:
                memory: "64Mi"
              requests:
                cpu: "10m"
                memory: "32Mi"

          storage:
            useAllNodes: false
            useAllDevices: false
            config:
              osdsPerDevice: "1"
            nodes:
              - name: "k8s-w-1"
                devices:
                  - name: "nvme0n1"
              - name: "k8s-w-2"
                devices:
                  - name: "nvme0n1"

          priorityClassNames:
            all: system-node-critical

  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph

  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
    ignoreDifferences:
      - kind: Secret
        jsonPointers:
          - /data
      - kind: ConfigMap
        jsonPointers:
          - /data
      - group: ceph.rook.io
        kind: CephCluster
        jsonPointers:
          - /status
      - group: ceph.rook.io
        kind: CephFilesystem
        jsonPointers:
          - /status
      - group: ceph.rook.io
        kind: CephBlockPool
        jsonPointers:
          - /status
      - group: ceph.rook.io
        kind: CephObjectStore
        jsonPointers:
          - /status

