apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-infra-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yordan-marinov/homelab.git
    targetRevision: HEAD
    path: infra/argocd/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
