apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pihole-secrets
  namespace: management
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-store
  target:
    name: pihole-web-password
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: /pihole/WEBPASSWORD
